### ISSUE TITLE
关于fork的疑问

### ISSUE THREAD

**Issue by Yougrianes** [njuics/java-2019-homeworks#206]
老师好！
我看了更新过后的README.md，关于本地的仓库，按照老师的意思，应该是需要clone我们所fork到自己账户下的分支仓库？
此外，pull命令的含义到底是将项目仓库的内容拉取到我的fork，还是将我的fork仓库做的变更合并到项目仓库中？那pull request是否会更新我的fork仓库呢？我如何保持我的分支仓库和老师的项目主仓库保持同步呢？
谢谢老师 :-D

**Comment by zero9931** [comment]
STFW

**Comment by Yougrianes** [comment]
关于这个问题昨天已经解决了，忘记close这个问题了:-|  感觉自己git还不是太熟啊
